### ISSUE TITLE
Compiling / Genericizing

### ISSUE THREAD

**Issue by HySpeed** [Barinzaya/twitch-rcon#1]
Hi,

I'm learning how Factorio integration works and I see you've created an RCON client for Space Destructor.

Can you share with me how to compile your code here?  (I assume .rs is Rust.)
Also, I'd love to learn how to make this a bit more generic so I can use it with [Silent Storm's Integration Helper](https://github.com/Sil3ntStorm/factorio-integration-helper#teleport_distance) mod.

thanks

**Comment by Barinzaya** [comment]
It is indeed written in Rust. If you have Rust installed, compiling it should just be a matter of running `cargo build` in the repository directory. If not, see [their site](https://www.rust-lang.org/tools/install) for instructions on how to install it. There are also pre-compiled executables of this tool for Windows available in [the Releases section here on GitHub](https://github.com/Barinzaya/twitch-rcon/releases); you can find it on the bar on the right side when you're on the main repo page. I should be able to easily cross-compile it as well, if you're not running Windows.

The general flow of how the integration works is relatively simple. The only way that I had found in my research to communicate with Factorio externally is to use the RCON protocol. This was intended to allow for running console commands on Factorio dedicated servers for administration purposes, but it can be used to run any defined console command. Clusterio and FactorioMMO, two of the largest integrations that I'm aware of, also use this method. RCON can also be used with locally-hosted multiplayer servers, though it has to be enabled in Factorio's settings (the hidden part). Hold Ctrl+Alt and click on Settings on the main menu, then go to "The Rest". The settings for RCON in local multiplayer are `local-rcon-socket` and `local-rcon-password`. RCON can't be used in a singleplayer game, to my knowledge.

This program uses RCON to connect to the Factorio server and run commands. Looking at the Integration Helper you linked, it seems as if it provides an interface via Factorio's `remote` API, which is only available to Lua. You can send `/c` commands via RCON, which allow you to run any Lua code (including calling stuff via `remote`), but using that command is considered cheating by Factorio and will disable achievements on the save game. The alternative is a mod for Factorio which defines new console commands that can be called via RCON (e.g. [Spacedestructor's mod](https://github.com/Spacedestructor/Spacedestructor-Factorio-Stream-Integration), with which this was co-developed). Installing any mod will switch you to a separate set of completed achievements from vanilla that won't give Steam achievements, but still does allow for achievements.

This program has some help for formatting commands in a "nice" way in the configuration, but it's written such that you can also just manually configure the exact command string you want to send, so it *probably* wouldn't need to be generalized in that regard unless you need commands to be able to incorporate redeem text or you need some kind of back-and-forth communication with a mod. But it does only support triggering of commands via Twitch channel point redeems, so if you wanted other means of triggering them, this may not be adequate. If you're not familiar with Rust, trying to jump in and make modifications will likely prove difficult, but there are likely libraries for the RCON protocol available in other languages as well. The general idea of using RCON to trigger console commands that trigger in-game effects will be the same.

**Comment by HySpeed** [comment]
thank you for all of that info.  that's some great knowledge and I appreciate you taking the time to explain it all.
